# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build    variables:
    - name: Tag
      value: $(Build.BuildId)
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:      
    - script: |
        envsubst '${Tag}' < node-deployment-template.yaml > node-deployment.yaml
      displayName: Replace Environment Vriables

    - task: Docker@2
      displayName: Build an image
      inputs:
          containerRegistry: 'dockerhub'
          repository: 'kaaras/node-app'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            latest
            $(Build.BuildId)
      
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'artifact'
        publishLocation: 'pipeline'